routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',"RegistroController@index");
Route::get('registro/listedit', "RegistroController@listedit");
Route::get('registro/eliminar', "RegistroController@eliminar");
Route::resource('registro', "RegistroController");

app/Registro.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Registro extends Model
{
	protected $table = "empresa";
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/RegistroController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Registro;

class RegistroController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $path = "registro";

    public function index()
    {
        //
        $data = Registro::all();
        //Enviamos esos registros a la vista.
        return view($this->path.'.index', compact('data')); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view($this->path.'.create');
    }

    public function listedit()
    {
        //
        $data = Registro::all();
        return view($this->path.'.listedit', compact('data'));
    }

    public function eliminar()
    {
        //
        $data = Registro::all();
        return view($this->path.'.eliminar', compact('data'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        try{
            $empresa = new Registro();
        
            $empresa->nombre = $request->nombre;
            $empresa->tipologia = $request->tipologia;
            $empresa->pais = $request->pais;
            $empresa->estado = $request->estado;
            $empresa->ciudad = $request->ciudad;
            $empresa->email_user = $request->email;
            $empresa->passw = $request->pass;
            $empresa->descripcion = $request->descripcion;
            $empresa->created_at = date('Y-m-d H:i:s');
            $empresa->updated_at = date('Y-m-d H:i:s');
            $empresa->save();

            return redirect()->route('registro.index');
        } catch (Exception $e) {
            return "Fatal error... ";$e.getMessage();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $empresa = Registro::findOrFail($id);
        return view($this->path.'.edit', compact('empresa'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $empresa = Registro::findOrFail($id);

        $empresa->nombre = $request->nombre;
        $empresa->tipologia = $request->tipologia;
        $empresa->pais = $request->pais;
        $empresa->estado = $request->estado;
        $empresa->ciudad = $request->ciudad;
        $empresa->email_user = $request->email;
        $empresa->passw = $request->pass;
        $empresa->descripcion = $request->descripcion;
        $empresa->created_at = date('Y-m-d H:i:s');
        $empresa->updated_at = date('Y-m-d H:i:s');
        $empresa->save();

        return redirect()->route('registro.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        try {
            $empresa = Registro::findOrFail($id);
            $empresa -> delete();
            return redirect()->route('registro.index');

        } catch (Exception $e) {
            return "Fatal error... ";$e.getMessage();
        }
    }
}

resources/views/empresa.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Prueba PHP</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<!--<link href='http://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700' rel='stylesheet' type='text/css'>-->
	<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="http://code.jquery.com/jquery-3.1.1.min.js"></script>
	<script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   @yield('estilos')
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="" style="margin-top:35px">
		
      <!-- Static navbar -->
      <nav class="navbar navbar-default" role="navigation">
        <div class="">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="#">INICIO</a></li>
              <li class="desk"><a>|</a></li>
              <li class="active dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">EMPRESAS <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="{{ route('registro.index') }}">LISTA DE EMPRESAS</a></li>
                  <li><a href="{{ route('registro.create') }}">REGISTRO DE EMPRESAS</a></li>
                  <li><a href="{{ url('registro/listedit') }}">ACTUALIZACION DE EMPRESAS</a></li>
                  <li><a href="{{ url('registro/eliminar') }}">ELIMINACIÓN DE EMPRESAS</a></li>
                </ul>
              </li>
              <li class="desk"><a>|</a></li>
              <li><a href="#">SERVICIOS</a></li>
              <li class="desk"><a>|</a></li>
              <li><a href="#">VALORA UN SERVICIO</a></li>
              <li class="desk"><a>|</a></li>
              <li><a href="#">CONTACTO</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="background-color:#5bc0de">
              <li><a href="#"  style="color:#fff">Registro</a></li>
              <li class="desk"><a style="color:#fff">|</a></li>
              <li><a href="#" style="color:#fff">Iniciar sesión</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
      </div>
      <div class="col-md-12 back-color-w" style="margin-top:20px;padding-bottom:40px;padding-top:8px">
         @yield('contenido')
      </div>
			<div class="col-md-12 back-color-w" style="padding-top:10px;margin-top:40px;margin-bottom:60px;color:#aaa">
        <div class="row">
        <div class="col-md-12">
          <div class="col-md-2"></div>
          <div class="col-md-10" style="padding:0">
				    <div class="col-md-3"><h4>Empresas</h4><p>Consequat<br>Nunc tempor<br>Ante quis libero<br>Fermentum</p></div>
				    <div class="col-md-3"><h4>Servicios</h4><p>Set congue suscipit<br>Consequat<br>Nunc tempor<br>Ante quis libero<br>Fermentum</p></div>
				    <div class="col-md-3"><h4>Valora un servicio</h4><p>Set congue suscipit<br>Consequat<br>Nunc tempor<br>Ante quis libero<br>Fermentum<br>Rhoncus dolor mattis<br>Nullam pellentesque<br>interdum ipsum ac</p></div>
				    <div class="col-md-3"><h4>Contacto</h4><p>Ante quis libero<br>Fermentum<br>Rhoncus dolor mattis<br>Nullam pellentesque<br>interdum ipsum ac</p></div>
          </div>
        </div>
        </div>
        <div class="row">
          <br><br>
          <div class="col-md-12">
          <div class="col-md-2"></div>
				  <div class="col-md-10"><p>Opiniones y consejos sobre servicios sanitarios, funerarios y mucho mas...<br>&copy; <?=date('Y')?> Todos los derechos reservados. <a href="#">Condiciones de uso</a>, <a href="#">Polítca de privacidad</a> y <a href="#">Política de cookies</a><br><br>Set tincidunt velit a accumsan laoreet. Donec vitae est quis ante rhoncus cursus non id ante. Nam fringilla euismod dui, non ullamcorper nunc.<br>Nullam id vestibulum orci, id porttitor lectus. Maecenas scelerisque dignissim erat et faucibus. Cras malesuada non massa ac lobortis.</p>
          </div>
        </div>
        </div>
        <div class="row">
          <br><br>
				  <div class="col-md-12" style="text-align:center">VERITUS&copy; 2017</div>
          <br><br>
        </div>
        </div>
			</div>
		</div>
	</div>
</body>
</html>

resources/views/registro/create.blade.php
@extends('empresa')
@section('estilos')<link rel="stylesheet" href="../CSS/estilos.css">@stop
@section('contenido')
<form method="post" action="{{ route('registro.store') }}">
  <input type="hidden" name="_token" value="{{ csrf_token() }}">
  <div class="col-md-10"><h3>REGISTRO DE EMPRESAS</h3></div>
  <div class="col-md-2" style="margin-top:12px;">
    <input type="submit" name="" value="Guardar Cambios" class="btn btn-primary"></div>
  <div class="col-md-12"><hr></div>
  <div class="col-md-8">
    <h4>INFORMACIÓN BÁSICA</h4>
    <div class="back-color-b" style="padding:8px 10px 15px 10px">
    <div class="row">
	     <div class="col-md-6">
        <h4>Nombre comercial de la empresa</h4>
        <input type="text" name="nombre" required>
       </div>
	   <div class="col-md-6"> 
        <h4>Tipología de la empresa</h4>
            <select id="tipologia" name="tipologia">
              <option value="Sociedad anonima (SA)">Sociedad anonima (SA)</option>
              <option value="Compañia anonima (CA)">Compañia anonima (CA)</option>
            </select>
      </div>
    </div>
    <div class="row">
            <div class="col-md-4">
            <h4>Pais</h4>
            <select id="" name="pais">
              <option value="Argentina">Argentina</option>
              <option value="Bolivia">Bolivia</option>
              <option value="Chile">Chile</option>
              <option value="Colombia">Colombia</option>
              <option value="Ecuador">Ecuador</option>
              <option value="Mexico">Mexico</option>
              <option value="Peru">Perú</option>
              <option value="Venezuela">Venezuela</option>
            </select>
            </div>
            <div class="col-md-4">
            <h4>Estado</h4>
            <input type="text" name="estado" required>
            </div>
            <div class="col-md-4">
            <h4>Ciudad</h4>
            <input type="text" name="ciudad" required>
            </div>
    </div>
    </div>
    <br>
    <h4>INFORMACIÓN REGISTRO</h4>
    <div class="back-color-b" style="padding:8px 10px 15px 10px">
    <div class="row">
      <div class="col-md-4">
        <h4>Email/Usuario</h4>
        <input type="email" name="email" required>
      </div>
      <div class="col-md-4">
        <h4>Password</h4>
        <input type="password" name="pass" required>
      </div>
      <div class="col-md-4">
        <h4>Repetir Password</h4> 
        <input type="password" name="pass" required>
      </div>
    </div>
    </div>
    </div>
            <div class="col-md-4" style="margin-top:40px">
            <div class="col-md-12 back-color-b" style="padding:8px 10px 8px 10px;">
              <h4>Descripcion de la empresa</h4>
              <textarea name="descripcion" style="width:100%;height:239px;resize:none" placeholder="255 caracteres"></textarea>
            </div>
            </div>

</form>
@stop

resources/views/registro/edit.blade.php
@extends('empresa')
@section('estilos')<link rel="stylesheet" href="../../CSS/estilos.css">@stop
@section('contenido')
<form method="post" action="{{ route('registro.update',$empresa->id) }}">
	<input type="hidden" name="_method" value="PUT">
	<input type="hidden" name="_token" value="{{ csrf_token() }}">
	<div class="col-md-10"><h3>ACTUALIZACIÓN DE EMPRESAS</h3></div>
  	<div class="col-md-2" style="margin-top:12px;">
    <button class="btn btn-primary" type="submit">Actualizar datos</button></div>
    <div class="col-md-12"><hr></div>
	<div class="col-md-8">
    <h4>INFORMACIÓN BÁSICA</h4>
    <div class="back-color-b" style="padding:8px 10px 15px 10px">
    <div class="row">
	     <div class="col-md-6">
        <h4>Nombre comercial de la empresa</h4>
        <input type="text" name="nombre" required value="{{ $empresa->nombre }}">
       </div>
	   <div class="col-md-6"> 
        <h4>Tipología de la empresa</h4>
            <select id="tipologia" name="tipologia">
              <option value="Sociedad anonima (SA)">Sociedad anonima (SA)</option>
              <option value="Compañia anonima (CA)">Compañia anonima (CA)</option>
            </select>
      </div>
    </div>
    <div class="row">
            <div class="col-md-4">
            <h4>Pais</h4>
            <select id="" name="pais">
              <option value="Argentina">Argentina</option>
              <option value="Bolivia">Bolivia</option>
              <option value="Chile">Chile</option>
              <option value="Colombia">Colombia</option>
              <option value="Ecuador">Ecuador</option>
              <option value="Mexico">Mexico</option>
              <option value="Peru">Perú</option>
              <option value="Venezuela">Venezuela</option>
            </select>
            </div>
            <div class="col-md-4">
            <h4>Estado</h4>
            <input type="text" name="estado" required value="{{ $empresa->estado }}">
            </div>
            <div class="col-md-4">
            <h4>Ciudad</h4>
            <input type="text" name="ciudad" required value="{{ $empresa->ciudad }}">
            </div>
    </div>
    </div>
    <br>
    <h4>INFORMACIÓN REGISTRO</h4>
    <div class="back-color-b" style="padding:8px 10px 15px 10px">
    <div class="row">
      <div class="col-md-4">
        <h4>Email/Usuario</h4>
        <input type="email" name="email" required value="{{ $empresa->email_user }}">
      </div>
      <div class="col-md-4">
        <h4>Password</h4>
        <input type="password" name="pass" required>
      </div>
      <div class="col-md-4">
        <h4>Repetir Password</h4> 
        <input type="password" name="pass" required>
      </div>
    </div>
    </div>
    </div>
            <div class="col-md-4" style="margin-top:40px">
            <div class="col-md-12 back-color-b" style="padding:8px 10px 8px 10px;">
              <h4>Descripcion de la empresa</h4>
              <textarea name="descripcion" style="width:100%;height:239px;resize:none">{{ $empresa->descripcion }}</textarea>
            </div>
            </div>
</form>
@stop

resources/views/registro/eliminar.blade.php
@extends('empresa')
@section('estilos')<link rel="stylesheet" href="../CSS/estilos.css">@stop
@section('contenido')
<div class="col-md-12">
<h3>LISTA DE EMPRESAS</h3>
<hr>
<div class="table-responsive">
<table class="table">
	<thead>
		<tr>
			<th>Nombre</th>
			<th>Tipologia</th>
			<th>Pais</th>
			<th>Estado</th>
			<th>Ciudad</th>
			<th>Email/Usuario</th>
			<th>Descripcion</th>
		</tr>
	</thead>
	<tbody>
	@foreach ($data as $row)
		<tr>
			<td>{{ $row->nombre }}</td>
			<td>{{ $row->tipologia }}</td>
			<td>{{ $row->pais }}</td>
			<td>{{ $row->estado }}</td>
			<td>{{ $row->ciudad }}</td>
			<td>{{ $row->email_user }}</td>
			<td>{{ $row->descripcion }}</td>
			<td>
			<form action="{{route('registro.destroy', $row->id)}}" method="post">
				<input type="hidden" name="_method" value="DELETE">
				<input type="hidden" name="_token" value="{{csrf_token()}}">
				<button class="btn btn-danger">Eliminar</button>
			</form>
		</tr>
	@endforeach
	</tbody>
</table>
</div>
</div>
@stop

resources/views/registro/index.blade.php
@extends('empresa')
@section('estilos')<link rel="stylesheet" href="./CSS/estilos.css">@stop
@section('contenido')
<div class="col-md-12">
<h3>LISTA DE EMPRESAS</h3>
<hr>
<div class="table-responsive">
<table class="table">
	<thead>
		<tr>
			<th>Nombre</th>
			<th>Tipologia</th>
			<th>Pais</th>
			<th>Estado</th>
			<th>Ciudad</th>
			<th>Email/Usuario</th>
			<th>Descripcion</th>
		</tr>
	</thead>
	<tbody>
	@foreach ($data as $row)
		<tr>
			<td>{{ $row->nombre }}</td>
			<td>{{ $row->tipologia }}</td>
			<td>{{ $row->pais }}</td>
			<td>{{ $row->estado }}</td>
			<td>{{ $row->ciudad }}</td>
			<td>{{ $row->email_user }}</td>
			<td>{{ $row->descripcion }}</td>
		</tr>
	@endforeach
	</tbody>
</table>
</div>
</div>
@stop

resources/views/registro/listedit.blade.php
@extends('empresa')
@section('estilos')<link rel="stylesheet" href="../CSS/estilos.css">@stop
@section('contenido')
<div class="col-md-12">
<h3>ACTUALIZACION DE EMPRESAS</h3>
<hr>
<div class="table-responsive">
<table class="table">
	<thead>
		<tr>
			<th>Nombre</th>
			<th>Tipologia</th>
			<th>Pais</th>
			<th>Estado</th>
			<th>Ciudad</th>
			<th>Email/Usuario</th>
			<th>Descripcion</th>
		</tr>
	</thead>
	<tbody>
	@foreach ($data as $row)
		<tr>
			<td>{{ $row->nombre }}</td>
			<td>{{ $row->tipologia }}</td>
			<td>{{ $row->pais }}</td>
			<td>{{ $row->estado }}</td>
			<td>{{ $row->ciudad }}</td>
			<td>{{ $row->email_user }}</td>
			<td>{{ $row->descripcion }}</td>
			<td><a href="{{ route('registro.edit',$row->id) }}" class="btn btn-info">Editar</a></td>
		</tr>
	@endforeach
	</tbody>
</table>
</div>
</div>
@stop